name: sbs-marketing-dev

networks:
  development:
    driver: bridge

services:
  sbs-dev:
    container_name: sbs-marketing-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    networks:
      - development
