name: sbs-marketing-dev

networks:
  sbs-marketing-dev:
    driver: bridge

services:
  sbs-dev:
    container_name: sbs-marketing-dev-database
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3305:3306
    networks:
      - sbs-marketing-dev
